In [1]:
import numpy as np


In [3]:
array1=np.array([[2,3,4],[5,6,7],[8,9,20]])

In [4]:
#  basic indexing, stepwise  ( start: stop: step)
#  step
array1[0:1]

array([[2, 3, 4]])

In [5]:
array1[0:1,1]

array([3])

In [6]:
array1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 20]])

In [7]:
array1[::2]

array([[ 2,  3,  4],
       [ 8,  9, 20]])

In [8]:
#  condition over my numpy filter the data

array1[::2] > 5

array([[False, False, False],
       [ True,  True,  True]])

In [10]:

array1 [ array1[::] > 5 ]

array([ 6,  7,  8,  9, 20])

In [11]:
array1[::] > 5

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [12]:
array1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 20]])

In [14]:
array1 [ array1[::] > 5 ].shape

(5,)

In [15]:
#  array1 => filter condition => it doesn;t know what type value are going to be matched
#  array1 => flattern the data

array1 [ array1[::] > 5 ]

array([ 6,  7,  8,  9, 20])

In [ ]:
array1 [ array1[1,:] > 5 ]

In [20]:
array1[ array1[1,:] >5 ]

array([[ 5,  6,  7],
       [ 8,  9, 20]])

In [18]:
array1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 20]])

In [21]:
array1[ array1[:,:] % 2 ==0  ]

array([ 2,  4,  6,  8, 20])

In [22]:
np.empty(shape=(3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.72718670e-321],
       [7.56592337e-307, 9.34588060e-307, 3.62651150e-317]])

In [23]:
np.empty(shape=(3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.72718670e-321],
       [7.56592337e-307, 9.34588060e-307, 3.62651150e-317]])

In [25]:
np.zeros(shape=(3,3)).dtype

dtype('float64')

In [26]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.full(fill_value="Abc",shape=(3,3))

array([['Abc', 'Abc', 'Abc'],
       ['Abc', 'Abc', 'Abc'],
       ['Abc', 'Abc', 'Abc']], dtype='<U3')

In [33]:
array1=np.array([[2,3,4],[5,6,7],[8,9,20]])

In [34]:
array1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 20]])

In [35]:
np.empty_like(array1)

array([[      0,       1,       0],
       [5570652,     624,       0],
       [    768,       0,       0]])

In [36]:
np.empty_like(array1)

array([[        1,         1,         0],
       [976301616,       660,         0],
       [ 16777984,     32760,         0]])

In [37]:
np.ones_like(array1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
np.loadtxt("Lending-company.csv",delimiter=",", dtype=np.str)

C:\Users\Tushar\AppData\Local\Temp\ipykernel_10204\3705783193.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.loadtxt("Lending-company.csv",delimiter=",", dtype=np.str)


array([['LoanID', 'StringID', 'Product', ..., 'AmtPaid60', 'AmtPaid360',
        'LoanStatus'],
       ['1', 'LoanID_1', 'Product B', ..., '4166', '14621', 'Active'],
       ['2', 'LoanID_2', 'Product D', ..., '4096', '16041', 'Active'],
       ...,
       ['1041', 'LoanID_1041', 'Product A', ..., '5143', '16617',
        'Finished Payment'],
       ['1042', 'LoanID_1042', 'Product B', ..., '3462', '15617',
        'Finished Payment'],
       ['1043', 'LoanID_1043', 'Product A', ..., '4743', '16617',
        'Finished Payment']], dtype='<U16')

In [44]:
lendingFile = np.genfromtxt("Lending-company.csv",delimiter=",")

In [45]:
print(lendingFile)

[[       nan        nan        nan ...        nan        nan        nan]
 [1.0000e+00        nan        nan ... 4.1660e+03 1.4621e+04        nan]
 [2.0000e+00        nan        nan ... 4.0960e+03 1.6041e+04        nan]
 ...
 [1.0410e+03        nan        nan ... 5.1430e+03 1.6617e+04        nan]
 [1.0420e+03        nan        nan ... 3.4620e+03 1.5617e+04        nan]
 [1.0430e+03        nan        nan ... 4.7430e+03 1.6617e+04        nan]]


In [46]:
#  4.1660 * 10**3
# 4.1660*1000 => 4166

lendingFile = np.genfromtxt("Lending-company.csv",delimiter=",", dtype=np.int32)

print(lendingFile)

[[   -1    -1    -1 ...    -1    -1    -1]
 [    1    -1    -1 ...  4166 14621    -1]
 [    2    -1    -1 ...  4096 16041    -1]
 ...
 [ 1041    -1    -1 ...  5143 16617    -1]
 [ 1042    -1    -1 ...  3462 15617    -1]
 [ 1043    -1    -1 ...  4743 16617    -1]]


In [47]:
lendingFile = np.genfromtxt("Lending-company.csv",delimiter=",", dtype=np.str)

print(lendingFile)

[['LoanID' 'StringID' 'Product' ... 'AmtPaid60' 'AmtPaid360' 'LoanStatus']
 ['1' 'LoanID_1' 'Product B' ... '4166' '14621' 'Active']
 ['2' 'LoanID_2' 'Product D' ... '4096' '16041' 'Active']
 ...
 ['1041' 'LoanID_1041' 'Product A' ... '5143' '16617' 'Finished Payment']
 ['1042' 'LoanID_1042' 'Product B' ... '3462' '15617' 'Finished Payment']
 ['1043' 'LoanID_1043' 'Product A' ... '4743' '16617' 'Finished Payment']]


C:\Users\Tushar\AppData\Local\Temp\ipykernel_10204\3187911927.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lendingFile = np.genfromtxt("Lending-company.csv",delimiter=",", dtype=np.str)


In [48]:
lendingFile = np.genfromtxt("Lending-company.csv",delimiter=",", dtype=np.object)

print(lendingFile)

[[b'LoanID' b'StringID' b'Product' ... b'AmtPaid60' b'AmtPaid360'
  b'LoanStatus']
 [b'1' b'LoanID_1' b'Product B' ... b'4166' b'14621' b'Active']
 [b'2' b'LoanID_2' b'Product D' ... b'4096' b'16041' b'Active']
 ...
 [b'1041' b'LoanID_1041' b'Product A' ... b'5143' b'16617'
  b'Finished Payment']
 [b'1042' b'LoanID_1042' b'Product B' ... b'3462' b'15617'
  b'Finished Payment']
 [b'1043' b'LoanID_1043' b'Product A' ... b'4743' b'16617'
  b'Finished Payment']]


C:\Users\Tushar\AppData\Local\Temp\ipykernel_10204\1366719838.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lendingFile = np.genfromtxt("Lending-company.csv",delimiter=",", dtype=np.object)


In [51]:
lendingFile = np.genfromtxt("Lending-company.csv",delimiter=",", 
                            dtype=(np.float, np.str,np.str,np.str,np.str,np.str,np.str,np.str   ))

print(lendingFile)

[(      nan, '', '', '', '', '', '', '')
 (1.000e+00, '', '', '', '', '', '', '')
 (2.000e+00, '', '', '', '', '', '', '') ...
 (1.041e+03, '', '', '', '', '', '', '')
 (1.042e+03, '', '', '', '', '', '', '')
 (1.043e+03, '', '', '', '', '', '', '')]


C:\Users\Tushar\AppData\Local\Temp\ipykernel_10204\3658592924.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=(np.float, np.str,np.str,np.str,np.str,np.str,np.str,np.str   ))
C:\Users\Tushar\AppData\Local\Temp\ipykernel_10204\3658592924.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=(np.float, np.str,np.str,np.str,np.str,np.st

In [52]:
lendingFile = np.genfromtxt("Lending-company.csv",delimiter=",")

print(lendingFile)

[[       nan        nan        nan ...        nan        nan        nan]
 [1.0000e+00        nan        nan ... 4.1660e+03 1.4621e+04        nan]
 [2.0000e+00        nan        nan ... 4.0960e+03 1.6041e+04        nan]
 ...
 [1.0410e+03        nan        nan ... 5.1430e+03 1.6617e+04        nan]
 [1.0420e+03        nan        nan ... 3.4620e+03 1.5617e+04        nan]
 [1.0430e+03        nan        nan ... 4.7430e+03 1.6617e+04        nan]]


In [53]:
np.isnan(lendingFile)

array([[ True,  True,  True, ...,  True,  True,  True],
       [False,  True,  True, ..., False, False,  True],
       [False,  True,  True, ..., False, False,  True],
       ...,
       [False,  True,  True, ..., False, False,  True],
       [False,  True,  True, ..., False, False,  True],
       [False,  True,  True, ..., False, False,  True]])

In [54]:
# Lending-company-Numeric.csv

lending_NumbericFile = np.genfromtxt("Lending-company-Numeric.csv",delimiter=",")

In [55]:
print(lending_NumbericFile)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [64]:
np.isnan(lending_NumbericFile).sum()

0

In [61]:
a1 = np.array([False,True,True,True])

In [62]:
a1.sum()

3

In [63]:
#  false=0 , true=1
a1

array([False,  True,  True,  True])

In [72]:
# Lending-company-Numeric-NAN.csv

lending_NumbericFile_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv",delimiter=";",
                                        filling_values=0)

In [73]:
lending_NumbericFile_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [    0.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [74]:
np.isnan(lending_NumbericFile_nan).sum()

0

In [84]:
# User=> 1,  user=0 ( NAN => 0)

#  prefer to change nan => mean or more than the maximum

array1=np.array([[2,3,4],[5,6,7],[8,9,20]])

In [76]:
array1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 20]])

In [78]:
np.mean(array1,axis=0)

array([ 5.        ,  6.        , 10.33333333])

In [79]:
np.mean(array1,axis=1)

array([ 3.        ,  6.        , 12.33333333])

In [80]:


import pandas as pd

In [81]:
pd.DataFrame([1,2,3]).dropna()

0
0  1
1  2
2  3

In [92]:

lending_NumbericFile_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv",delimiter=";",
                                       filling_values=meanLending)

In [90]:
meanLending = np.nanmean(lending_NumbericFile_nan, axis=0).round(2)[0]

In [91]:
# outlier
meanLending

2250.25

In [93]:
lending_NumbericFile_nan

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [94]:
np.nanmean(lending_NumbericFile_nan)

4654.015659955257