In [5]:
import numpy as  np

In [6]:
# scalar

x=5

In [7]:
vector1 = np.array( [2,3,4,5] )

vector1

array([2, 3, 4, 5])

In [8]:
np.array( (3,4,5,6) )

array([3, 4, 5, 6])

In [9]:
type(vector1)

numpy.ndarray

In [11]:
matrix1 = np.array([ 
                [4,2,3],
                  [3,4,5]  ])

In [12]:
matrix1

array([[4, 2, 3],
       [3, 4, 5]])

In [13]:
matrix1.shape

(2, 3)

In [14]:
vector1.shape

(4,)

In [15]:
vector1

array([2, 3, 4, 5])

In [16]:
vector1.shape

(4,)

In [18]:
x = vector1.reshape(1,4)
print(x)
x.shape

[[2 3 4 5]]


(1, 4)

In [19]:
x.reshape(4,1)

array([[2],
       [3],
       [4],
       [5]])

In [20]:
v1= np.array([2,4,6])
v2=np.array([1,7,4])

np.dot(v1,v2)

54

In [21]:
matrix1.dtype

dtype('int32')

In [27]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [28]:
#  zeros, one, fill

In [29]:
matrix1

array([[4, 2, 3],
       [3, 4, 5]])

In [34]:

matrix1[0:,0:1]

array([[4],
       [3]])

In [36]:

np.array([1,2.0,"A"])

array(['1', '2.0', 'A'], dtype='<U32')

In [38]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [39]:
np.arange(2,6)

array([2, 3, 4, 5])

In [41]:
arr1 = np.arange(1,6,2)

In [42]:
arr1

array([1, 3, 5])

In [43]:
arr1.shape

(3,)

In [46]:
arr1 = np.arange(2,26,2)

In [47]:
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [50]:
arr1.shape

(12,)

In [53]:
arr1 =arr1.reshape(3,4)

In [54]:
arr1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [58]:
b= arr1.T
b

array([[ 2, 10, 18],
       [ 4, 12, 20],
       [ 6, 14, 22],
       [ 8, 16, 24]])

In [59]:
for data in np.nditer(b):
    print(data)

2
4
6
8
10
12
14
16
18
20
22
24


In [57]:
for data in np.nditer(arr1):
    print(data)

2
4
6
8
10
12
14
16
18
20
22
24


In [60]:
#  tensor => combination of multiple matrix