In [1]:
import numpy as np

In [3]:
array1=np.array([[2,3,4],
         [4,5,6]])

In [4]:
array1

array([[2, 3, 4],
       [4, 5, 6]])

In [5]:

array1.shape

(2, 3)

In [8]:
array1[0][1] =99

In [9]:
array1

array([[ 2, 99,  4],
       [ 4,  5,  6]])

In [11]:

array1[ -1 ] 

array([4, 5, 6])

In [18]:
array1[0:,1]=88

In [19]:
array1

array([[ 2, 88,  4],
       [ 4, 88,  6]])

In [20]:

array1[:]=9

In [21]:

array1

array([[9, 9, 9],
       [9, 9, 9]])

In [23]:
# array1


list1=[10,20,30]

list1+[2]

[10, 20, 30, 2]

In [25]:
vector1 = np.array([2,3,4])

vector1+2

array([4, 5, 6])

In [26]:
array1=np.array([[4,6,8],[2,3,7]])

In [27]:
array1

array([[4, 6, 8],
       [2, 3, 7]])

In [29]:

vector1 = np.array([1,2,3])

vector1.shape

(3,)

In [30]:
np.add(vector1, array1)

array([[ 5,  8, 11],
       [ 3,  5, 10]])

In [31]:
a = np.zeros((3, 3), np.int)

C:\Users\Tushar\AppData\Local\Temp\ipykernel_19072\1418940240.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.zeros((3, 3), np.int)


In [32]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
b = np.arange(3)

b.shape

(3,)

In [37]:
b = b.reshape(1,3)

In [35]:
a+b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [39]:
b.shape

(1, 3)

In [41]:
np.add(a,b)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [42]:
a = np.zeros((2, 2), np.int)

C:\Users\Tushar\AppData\Local\Temp\ipykernel_19072\1339039896.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.zeros((2, 2), np.int)


In [43]:
a

array([[0, 0],
       [0, 0]])

In [45]:
#  b is column vector
b = np.arange(3)


In [46]:
a+b

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [47]:
b

array([0, 1, 2])

In [48]:
b.shape

(3,)

In [51]:
b=b.reshape(1,3)

In [52]:
b.shape

(1, 3)

In [53]:
a.shape

(2, 2)

In [54]:
# (1,3)   => (2,3)
#  (2,2)

In [61]:
array1 = np.zeros( (3,3))

In [62]:
array1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
b= np.array([ [10,20], [20,20] ])

In [64]:
b.shape

(2, 2)

In [65]:
b

array([[10, 20],
       [20, 20]])

In [67]:
# b is the smalller dimension  (2,2)

# a is  dimension (3,3)

array1+b


ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

In [68]:
vector1 = np.array([10,20,30])

In [69]:
vector1.shape

(3,)

In [70]:

vector1 = vector1.reshape(1,3)

In [71]:
vector1.shape

(1, 3)

In [73]:
array1.shape

#  max=3 row & columns

(3, 3)

In [74]:
vector1.ndim

2

In [75]:
array1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
array1+vector1

array([[10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.]])

In [77]:
vector1 = np.array([10,20,30])

In [78]:
vector1.shape

(3,)

In [79]:
vector1.ndim

1

In [80]:
vector1 + array1

array([[10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.]])

In [81]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [82]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:

vector1

array([10, 20, 30])

In [84]:
vector1+array1

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [89]:
newVector1 =vector1.reshape(3,1)

newVector1

array([[10],
       [20],
       [30]])

In [90]:
new1 =newVector1+array1

In [91]:
# (4,4)

# (1,4)

#  dimension reduction 

new1

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39]])

In [93]:
type(new1[0,0])

numpy.int32

In [95]:
type(new1[0,0:])

numpy.ndarray

In [96]:
new1[0,0:].shape

(3,)

In [97]:
new1[0,0:].ndim

1

In [121]:
new1[0,0:].shape

(3,)

In [125]:
new1[0,:].ndim

1

In [128]:
ac = new1[0,0:]
ac.ndim

# ac.shape

1

In [129]:
ac.shape

(3,)

In [131]:
np.squeeze(ac)

array([11, 12, 13])

In [140]:
array1 = np.arange( 1,8,1)

In [142]:
array1.squeeze()

array([1, 2, 3, 4, 5, 6, 7])